apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} # exposed to ingress
      targetPort: 3000  # container port
  selector:
    app: frontend