replicaCount: 2 # default number of pods to start with
image:
  repository: mern-chat-app-backend # docker repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001

env:
  - name: MONGO_URI
    valueFrom:
      secretKeyRef:
        name: chatapp-secrets
        key: uri

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60